name: Generate Snake Animation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark
      - uses: actions/upload-artifact@v3
        with:
          name: snake-artifacts
          path: github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: actions/checkout@v4

      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Updated snake animation" || echo "No changes to commit"
          git push origin output || echo "No changes to push"
